### PR TITLE
"Darker" variant of standard adementary-theme

### PR DESCRIPTION
**Pull request by SaucySauce**
No idea if what I'm doing is right but here it goes. Right now only changing 3.24 gtk.css file.

### CODE REVIEW

**Comment by SaucySauce** [comment]
Sorry, need to do more research on pull requests.

**Comment by SaucySauce** [comment]
Dumber than a sack of doodoo. 
Nemo status bar needs to be light.
Local menu bars aren't displaying proper font color but its context menus are.
Change the border of every window/popover/dialogbox/etc to the light color.
Classic title bars are still in light mode.
Budgie applets are a weird mix of light mode and dark mode, need to be in light mode.
CSD comboboxes are correct as dark but everywhere else they must be in light mode.

**Comment by hrdwrrsk** [comment]
Seems you're editing CSS file directly than editing `.scss` file and compile it to CSS (with `parse_sass.sh` script) but ok at all, this would be just experimental work and I will working with my version (a first task is making `_dark-widgets.scss` file or something like that)

**Comment by SaucySauce** [comment]
You mean the gtk.scss in 3.24 folder?

where would the _dark-widgets.scss file be? in the sass folder?

**Comment by SaucySauce** [comment]
What text editor do you use?

**Comment by SaucySauce** [comment]
Do I need to add '-darker' variant to install.sh and parse-sass.sh? Create index-darker.theme too?

**Comment by SaucySauce** [comment]
Maybe I'm way over my head with the way I was doing the changes, changing every CSS file is a pain.

**Comment by hrdwrrsk** [comment]
> What text editor do you use?

I use Sublime Text (previously using Atom/VSCode but RAM usage is heavy)

**Comment by hrdwrrsk** [comment]
> Do I need to add '-darker' variant to install.sh and parse-sass.sh? Create index-darker.theme too?

Yes.

**Comment by SaucySauce** [comment]
Thanks.

**Comment by hrdwrrsk** [comment]
> You mean the gtk.scss in 3.24 folder?
> 
> where would the _dark-widgets.scss file be? in the sass folder?

Yes. `_dark-widgets.scss` is placed on `sass` folder, also make sure you edit a `gtk.scss` file to include `_dark-widgets.scss`

Some examples:
```
@import '../../gtk-3.0/sass/colors';
@import '../../gtk-3.0/sass/drawing';
@import '../../gtk-3.0/sass/common';
@import '../../gtk-3.0/sass/dark-widgets';
@import '../../gtk-3.0/sass/applications';
@import '../../gtk-3.0/sass/budgie';
@import '../../gtk-3.0/sass/gnome-applications';
@import '../../gtk-3.0/sass/colors-public';

**Comment by SaucySauce** [comment]
Thanks. There's a light and dark gtk.scss, I created a darker gtk.scss. Similar to light gtk.scss but with light panel set to false.

**Comment by SaucySauce** [comment]
What has to be set in dark-widgets.scss?

**Comment by hrdwrrsk** [comment]
> What has to be set in dark-widgets.scss?

All variants should have but you need something like `@if $variant == 'darker'` etc. Or just look other Gtk+ theme like @horst3180's vertex-theme to see how dark headerbar coloring work, or maybe @godlyranchdressing's Aduru theme (it's also Adwaita-based)

**Comment by SaucySauce** [comment]
Thanks.

**Comment by SaucySauce** [comment]
Both haven't been updated in two years though.

**Comment by SaucySauce** [comment]
```
$variant: 'light';
$darker: true;

@import 'colors';
@import 'drawing';
@import 'common';
@import 'applications';
@import 'gnome-applications';
@import 'budgie';
@import 'palette';
@import 'colors-public';
```
looking at the other themes. _darker-widgets.scss something like this?

**Comment by SaucySauce** [comment]
```
$variant: 'darker';

@import 'colors';
@import 'drawing';
@import 'common';
@import 'applications';
@import 'gnome-applications';
@import 'budgie';
@import 'palette';
@import 'colors-public';
```
Or this?

**Comment by SaucySauce** [comment]
On vertex gtk.scss file the following comment

> // - if you need to inverse a color function use the @if directive to match for dark $variant

Is this editing common and set specific areas of darker theme with mix of "dark" in a "light" section?

**Comment by SaucySauce** [comment]
I'm looking at Aduru common.scss. Seems similar enough to yours. Do I add "@if $darker" sections from the Aduru to yours?

**Comment by SaucySauce** [comment]
Looks like my fork is diverging too much from this new gold info of yours. I've cloned your theme again and started doing the .scss changes and .sh 'darker' additions.

**Comment by SaucySauce** [comment]
How do I make a pull request of just the affected files and not a full fork request which I did with this one?

**Comment by SaucySauce** [comment]
Nevermind. Found a solution.

**Comment by SaucySauce** [comment]
A bit off topic but I got a hold of pixel saver applet support code.

**Comment by SaucySauce** [comment]
Finally got the darker version working, not the actual visual changes but rather the -darker compilers and it works with the light and dark assets, dark panel and light theme for a test. OR it could be scripts defaulting to standard theme BUT I'm damn sure it's not that. However, can't upload all the changes to git for some reason.

**Pull request closed without merging**
